# @Author: Popov Gennadiy <dio>
# @Date:   2016-11-28T00:57:24+03:00
# @Email:  me@westtrade.tk
# @Last modified by:   dio
# @Last modified time: 2016-12-21T21:17:45+03:00


version: '2'
services:
    docker-configurator:
        build: ./
        service-name: docker-configurator
