# @Author: Popov Gennadiy <dio>
# @Date:   2016-11-28T00:57:24+03:00
# @Email:  me@westtrade.tk
# @Last modified by:   dio
# @Last modified time: 2016-11-28T01:14:47+03:00


version: '2'
services:
    docker-configurator:
        build: ./
