# @Author: Popov Gennadiy <dio>
# @Date:   2016-11-28T00:57:24+03:00
# @Email:  me@westtrade.tk
# @Last modified by:   dio
# @Last modified time: 2016-12-22T00:10:55+03:00


version: '2'
services:


    docker-configurator:
        build: ./
        volumes:
            - /var/run/docker.sock:ro

        #https://github.com/lorenwest/node-config/wiki/Environment-Variables
        environment:
            DEBUG: docker-configurator
            NODE_CONFIG: '
                {
                    "socket-path": "/var/run/docker.sock"
                }
                '
