# @Author: Popov Gennadiy
# @Date:   2016-11-19T00:45:46+03:00
# @Email:  me@westtrade.tk
# @Last modified by:   dio
# @Last modified time: 2016-11-29T09:32:13+03:00

socket-path: /var/run/docker.sock
# threshold: 1000
# nginx_container: webfront
default_host: #DEFAULT_HOST

consul:
    host: 172.18.0.3

database:
    filename: ./.data/services.json
    autoload: true
