# @Author: Popov Gennadiy
# @Date:   2016-11-19T00:45:46+03:00
# @Email:  me@westtrade.tk
# @Last modified by:   dio
# @Last modified time: 2016-12-22T05:22:21+03:00

socket-path: /var/run/docker.sock
database:
    filename: ./.data/services.json
    autoload: true

templates: []
